# filebrowser configurations

# Address to listen on
#address = "127.0.0.1"

# The base path of visiting
# might be helpful when under a reverse proxy
#baseurl = ""

# TLS Certificate
#cert = ""

# The database location
# database = ""
# has been set to /var/lib/filebrowser/filebrowser.db
# this setting here is invalid, please change it in the
#     openrc config file: /etc/conf.d/filebrowser
#  or systemd service file: /lib/systemd/system/filebrowser.service

# TLS Key
#key = ""

# Log output
#log = "stdout"

# Port to listen on
#port = 8080

# The root browsing path
root = "/tmp"
